In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Dropout

In [12]:
df = pd.read_csv('Fertilizer Prediction.csv')

In [20]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  label  
0            0            Urea      6  
1           36             DAP      5  
2           30        14-35-14      1  
3           20           28-28      4  
4            0            Urea      6

In [21]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
df["label"] = lb_make.fit_transform(df["Fertilizer Name"])
print('done')

done


In [22]:
df

Temparature  Humidity   Moisture Soil Type    Crop Type  Nitrogen  \
0            26         52        38     Sandy        Maize        37   
1            29         52        45     Loamy    Sugarcane        12   
2            34         65        62     Black       Cotton         7   
3            32         62        34       Red      Tobacco        22   
4            28         54        46    Clayey        Paddy        35   
5            26         52        35     Sandy       Barley        12   
6            25         50        64       Red       Cotton         9   
7            33         64        50     Loamy        Wheat        41   
8            30         60        42     Sandy      Millets        21   
9            29         58        33     Black    Oil seeds         9   
10           27         54        28    Clayey       Pulses        13   
11           31         62        48     Sandy        Maize        14   
12           25         50        65     Loamy       Cotton        36   
13           32         62        41    Clayey        Paddy        24   
14           26         52        31       Red  Ground Nuts        14   
15           31         62        49     Black    Sugarcane        10   
16           33         64        34    Clayey       Pulses        38   
17           25         50        39     Sandy       Barley        21   
18           28         54        65     Black       Cotton        39   
19           29         58        52     Loamy        Wheat        13   
20           30         60        44     Sandy      Millets        10   
21           34         65        53     Loamy    Sugarcane        12   
22           35         68        33       Red      Tobacco        11   
23           28         54        37     Black      Millets        36   
24           33         64        39    Clayey        Paddy        13   
25           26         52        44     Sandy        Maize        23   
26           30         60        63       Red       Cotton         9   
27           32         62        30     Loamy    Sugarcane        38   
28           37         70        32     Black    Oil seeds        12   
29           26         52        36    Clayey       Pulses        14   
..          ...        ...       ...       ...          ...       ...   
69           30         60        38     Sandy      Millets        10   
70           26         52        39    Clayey       Pulses        21   
71           31         62        32       Red      Tobacco        39   
72           34         65        48     Loamy        Wheat        23   
73           27         53        34     Black    Oil seeds        42   
74           33         64        31       Red  Ground Nuts        13   
75           29         58        42    Clayey        Paddy         9   
76           30         60        47     Sandy        Maize        22   
77           27         53        59     Loamy    Sugarcane        10   
78           26         52        36    Clayey       Pulses         7   
79           34         65        63       Red       Cotton        14   
80           28         54        43    Clayey        Paddy        10   
81           30         60        40     Sandy      Millets        41   
82           29         58        65     Black       Cotton        14   
83           26         52        59     Loamy    Sugarcane        11   
84           31         62        44     Sandy       Barley        21   
85           35         67        28    Clayey       Pulses         8   
86           29         58        30       Red      Tobacco        13   
87           27         53        30     Black      Millets        35   
88           36         68        50     Loamy        Wheat        12   
89           29         58        61     Loamy       Cotton        11   
90           30         60        26     Black    Oil seeds         8   
91           34         65        45    Clayey        Paddy   

In [23]:
from sklearn.preprocessing import OneHotEncoder
df = pd.get_dummies(df, columns = ['Soil Type', 'Crop Type']) 

In [30]:
df.columns,len(df.columns)

(Index(['Temparature', 'Humidity ', 'Moisture', 'Nitrogen', 'Potassium',
        'Phosphorous', 'Fertilizer Name', 'label', 'Soil Type_Black',
        'Soil Type_Clayey', 'Soil Type_Loamy', 'Soil Type_Red',
        'Soil Type_Sandy', 'Crop Type_Barley', 'Crop Type_Cotton',
        'Crop Type_Ground Nuts', 'Crop Type_Maize', 'Crop Type_Millets',
        'Crop Type_Oil seeds', 'Crop Type_Paddy', 'Crop Type_Pulses',
        'Crop Type_Sugarcane', 'Crop Type_Tobacco', 'Crop Type_Wheat'],
       dtype='object'), 24)

In [26]:
df.head()

Temparature  Humidity   Moisture  Nitrogen  Potassium  Phosphorous  \
0           26         52        38        37          0            0   
1           29         52        45        12          0           36   
2           34         65        62         7          9           30   
3           32         62        34        22          0           20   
4           28         54        46        35          0            0   

  Fertilizer Name  label  Soil Type_Black  Soil Type_Clayey  ...  \
0            Urea      6                0                 0  ...   
1             DAP      5                0                 0  ...   
2        14-35-14      1                1                 0  ...   
3           28-28      4                0                 0  ...   
4            Urea      6                0                 1  ...   

   Crop Type_Cotton  Crop Type_Ground Nuts  Crop Type_Maize  \
0                 0                      0                1   
1                 0                      0                0   
2                 1                      0                0   
3                 0                      0                0   
4                 0                      0                0   

   Crop Type_Millets  Crop Type_Oil seeds  Crop Type_Paddy  Crop Type_Pulses  \
0                  0                    0                0                 0   
1                  0                    0                0                 0   
2                  0                    0                0                 0   
3                  0                    0                0                 0   
4                  0                    0                1                 0   

   Crop Type_Sugarcane  Crop Type_Tobacco  Crop Type_Wheat  
0                    0                  0                0  
1                    1                  0                0  
2                    0                  0                0  
3                    0                  1                0  
4                    0                  0                0  

[5 rows x 24 columns]

In [27]:
X = df.drop(['label','Fertilizer Name'],axis=1)
y = df['label']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
y.unique()

array([6, 5, 1, 4, 2, 3, 0], dtype=int64)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [34]:
model = Sequential()

model.add(Dense(units=22,input_dim=22, activation='relu'))

model.add(Dense(units=19,activation='relu'))

model.add(Dense(units=16,activation='relu'))

model.add(Dense(units=13,activation='relu'))

model.add(Dense(units=10,activation='relu'))

model.add(Dense(units=7,activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 22)                506       
_________________________________________________________________
dense_4 (Dense)              (None, 19)                437       
_________________________________________________________________
dense_5 (Dense)              (None, 16)                320       
_________________________________________________________________
dense_6 (Dense)              (None, 13)                221       
_________________________________________________________________
dense_7 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_8 (Dense)              (None, 7)                 77        
Total params: 1,701
Trainable params: 1,701
Non-trainable params: 0
____________________________________________________

In [36]:
history = model.fit(X_train, y_train, epochs=200, batch_size=64)

Epoch 1/200
2/2 [==============================] - 0s 1ms/step - loss: 6.4176 - accuracy: 0.1408
Epoch 2/200
2/2 [==============================] - 0s 2ms/step - loss: 2.0289 - accuracy: 0.1848
Epoch 3/200
2/2 [==============================] - 0s 2ms/step - loss: 1.9549 - accuracy: 0.1744
Epoch 4/200
2/2 [==============================] - 0s 2ms/step - loss: 1.9192 - accuracy: 0.1796
Epoch 5/200
2/2 [==============================] - 0s 4ms/step - loss: 1.9032 - accuracy: 0.1796
Epoch 6/200
2/2 [==============================] - 0s 9ms/step - loss: 1.8914 - accuracy: 0.1796
Epoch 7/200
2/2 [==============================] - 0s 2ms/step - loss: 1.8785 - accuracy: 0.1744
Epoch 8/200
2/2 [==============================] - 0s 6ms/step - loss: 1.8730 - accuracy: 0.1692
Epoch 9/200
2/2 [==============================] - 0s 6ms/step - loss: 1.8583 - accuracy: 0.1796
Epoch 10/200
2/2 [==============================] - 0s 3ms/step - loss: 1.8647 - accuracy: 0.1848
Epoch 11/200
2/2 [===========

Epoch 167/200
2/2 [==============================] - 0s 2ms/step - loss: 0.2068 - accuracy: 0.9341
Epoch 168/200
2/2 [==============================] - 0s 3ms/step - loss: 0.3473 - accuracy: 0.8346
Epoch 169/200
2/2 [==============================] - 0s 2ms/step - loss: 0.6021 - accuracy: 0.7687
Epoch 170/200
2/2 [==============================] - 0s 3ms/step - loss: 0.6356 - accuracy: 0.7791
Epoch 171/200
2/2 [==============================] - 0s 2ms/step - loss: 1.1741 - accuracy: 0.5853
Epoch 172/200
2/2 [==============================] - 0s 2ms/step - loss: 1.0485 - accuracy: 0.6213
Epoch 173/200
2/2 [==============================] - 0s 4ms/step - loss: 0.2448 - accuracy: 0.9431
Epoch 174/200
2/2 [==============================] - 0s 2ms/step - loss: 0.1739 - accuracy: 0.9716
Epoch 175/200
2/2 [==============================] - 0s 5ms/step - loss: 0.1959 - accuracy: 0.9678
Epoch 176/200
2/2 [==============================] - 0s 4ms/step - loss: 1.1371 - accuracy: 0.5569
Epoch 177/

In [37]:
from sklearn.metrics import classification_report,confusion_matrix

In [39]:
predictions = model.predict_classes(X_test)

C:\Users\abhis\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [40]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         1
           3       0.00      0.00      0.00         1
           4       0.86      1.00      0.92         6
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         6

    accuracy                           0.92        25
   macro avg       0.79      0.81      0.79        25
weighted avg       0.90      0.92      0.90        25



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [57]:
c = 0 
for col in X.columns:
    print(c,col)
    c += 1

0 Temparature
1 Humidity 
2 Moisture
3 Nitrogen
4 Potassium
5 Phosphorous
6 Soil Type_Black
7 Soil Type_Clayey
8 Soil Type_Loamy
9 Soil Type_Red
10 Soil Type_Sandy
11 Crop Type_Barley
12 Crop Type_Cotton
13 Crop Type_Ground Nuts
14 Crop Type_Maize
15 Crop Type_Millets
16 Crop Type_Oil seeds
17 Crop Type_Paddy
18 Crop Type_Pulses
19 Crop Type_Sugarcane
20 Crop Type_Tobacco
21 Crop Type_Wheat


In [69]:
for i in range(22):
    print(X.iloc[0][i],end=", ")

26, 52, 38, 37, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 

In [34]:
print(X.iloc[0],end=", ")

Temparature              26
Humidity                 52
Moisture                 38
Nitrogen                 37
Potassium                 0
Phosphorous               0
Soil Type_Black           0
Soil Type_Clayey          0
Soil Type_Loamy           0
Soil Type_Red             0
Soil Type_Sandy           1
Crop Type_Barley          0
Crop Type_Cotton          0
Crop Type_Ground Nuts     0
Crop Type_Maize           1
Crop Type_Millets         0
Crop Type_Oil seeds       0
Crop Type_Paddy           0
Crop Type_Pulses          0
Crop Type_Sugarcane       0
Crop Type_Tobacco         0
Crop Type_Wheat           0
Name: 0, dtype: int64, 

In [70]:
ans =model.predict([[26, 52, 38, 37, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [71]:
index_of_maximum = np.where(ans[0] == max(ans[0]))

In [72]:
index_of_maximum

(array([6], dtype=int64),)

In [74]:
model.predict([[26, 52, 38, 37, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

array([[1.9204793e-10, 9.9110789e-11, 4.5746080e-07, 5.5267629e-03,
        5.1644049e-04, 2.2033830e-13, 9.9395639e-01]], dtype=float32)

In [73]:
df['label'].unique()

array([6, 5, 1, 4, 2, 3, 0])

In [75]:
df['Fertilizer Name'].unique()

array(['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20',
       '10-26-26'], dtype=object)

In [76]:
from tensorflow.keras.models import load_model
model.save('fertilizer_model.h5') 

In [77]:
model = tf.keras.models.load_model('fertilizer_model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("fertilizer_model.tflite", "wb").write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\abhis\AppData\Local\Temp\tmp71ewa1na\assets


9832